beerpoint/beer_list/urls.py
from django.conf.urls import patterns, include, url


urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'beerpoint.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^beer/all/', 'beer_list.views.choose_all_beers', name='choose_all_beers'),
    url(r'^beer/get/(?P<beer_id>\d+)/$', 'beer_list.views.detail_beer', name='detail_beer'),
    url(r'^$', 'beer_list.views.choose_all_beers', name='choose_all_beers'),

)

beerpoint/beerpoint/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin




urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'beerpoint.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('beer_list.urls', namespace='beer_list')),

)

beerpoint/beer_list/models.py
# -*- coding: utf-8 -*-
from django.db import models

# Create your models here.
class BeerTable(models.Model):
    class Meta():
        db_table = 'beer_table'
    beer_name = models.CharField(verbose_name=' Название пива', max_length= 250)
    beer_maker = models.CharField(verbose_name='Произв', max_length=250)
    beer_country = models.CharField(verbose_name='Страна', max_length=250)
    beer_calory = models.IntegerField(verbose_name='Калории')
    beer_part_suslo = models.DecimalField(verbose_name='Часть сухих веществ', max_digits=4, decimal_places=1)
    beer_part_alco = models.DecimalField(verbose_name='Количество алкоголя от объема', max_digits=3, decimal_places=1)
    beer_another = models.TextField(verbose_name='Доп. информация')
    beer_date_public = models.DateTimeField(auto_now_add=True)

    def __unicode__(self):
        return u"%s %s %s %s %s %s %s %s" %(self.beer_name, self.beer_maker, self.beer_country, self.beer_calory, self.beer_part_suslo, self.beer_part_alco, self.beer_another, self.beer_date_public)

beerpoint/beer_list/views.py
# -*- coding: utf-8 -*-
from django.shortcuts import render_to_response
from models import BeerTable
from django.shortcuts import get_object_or_404
import random
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
# Create your views here.


"""
1. Вытягиваем все объекты с мускла
2. Делаем рандом по главной странице для всех напитков
3. выводим 6 штук
"""

def choose_all_beers(request):
    beers = BeerTable.objects.all().order_by('-beer_date_public')
    return render_to_response('beers.html', {"beers": beers})

"""
1. При нажатии на ссылку открываеться название пива и через регулярное выражение выбираем id пива.
2. Если нету id в базе вызываем 404
3. Если есть выводим через айти страницу определенного пива
"""
def detail_beer(request, beer_id):
    kind = get_object_or_404(BeerTable, pk=beer_id)
    return render_to_response('beer.html', {'kind': kind})

beerpoint/templates/beer.html
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title>{{ kind.id}} </title>
</head>
<body>
    <h2> {{ kind.beer_name }}</h2>
    <h4> {{ kind.beer_country }} </h4>
    <hr>
</body>
</html>

beerpoint/templates/beers.html
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title>Пивная энциклопедия </title>
</head>
<body>
    {% for beer in beers %}
    <h2> <a href="{% url 'beer_list:detail_beer' beer.id %}"> Название пива: {{ beer.beer_name }} </a></h2>
    <h4>Страна производитель: {{ beer.beer_country }} </h4>
    <hr>
    {% endfor %}
</body>
</html>

beerpoint/templates/main.html
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title>Пивная энциклопедия </title>
</head>
<body>

</body>
</html>